### ISSUE TITLE
Netsparker in  "Deployment"

### ISSUE THREAD

**Issue by davidvandersluis** [netsparker/Netsparker-Cloud-Bamboo-Plugin#1]
Reported to Netsparker as well, but added here for visibility and to avoid hair pulling by others using this plugin:

Currently the option to integrate Netsparker in Bamboo is limited to the "Build" step of a project. However, as Netsparker is a DAST, it seems more logical to add the Netsparker task into the deployment step: Netsparker needs a running instance of the project to be able to scan.

I've now resorted to implement a task (script) into Bamboo by calling the Netsparker API directly.

**Comment by duranserkan** [comment]
The plugin developed for continuous deployment. By using build plans for scanning we can obtain commit and committer info. We are using this values for issue assignment and reporting. However, supporting these features makes our existing scan task incompatible with deployment projects. We are planning to provide deployment projects with next releases since this feature requires development in Netsparker Cloud, as well as the plugin. You can use build plans with deployment tasks until then.
